language: python
python: 3.6
install: pip install -U tox-travis
script: tox
before_install:
- openssl aes-256-cbc -K $encrypted_09207bcf28b9_key -iv $encrypted_09207bcf28b9_iv
  -in config_example.ini.enc -out config_example.ini -d
