language: python
python: 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  user: dileep-kishore
  on:
    tags: true
  password:
    secure: JCM/lXv8YLB0MN7lNZlAnDZmylRcASj+/YY1bE1idVxNVi6yLKZMHG0JR10H0Mxc3WAfSu+JYdgeYPcW1LApI0J0HIL4XhZYU7pZEO99klRkcsctB2Y6KpriuYyhfci2orf7PBeUAKgRNcvuNEYS+befNNcR+Lv9Pjf525OTW+W669vlf3D/P0ItLcdmz7OS3Cka5QZKijS5Luo1y1SgdCea7gjt8nTOJu6ywGtSN0A8L7/pXpiaidIRixAf8i+etqLKd4syUtHedk+Ngwa0gMSQZavG8joRv77hcxMXtNG2tOLdAizgA4383eUjyh+Xr2o2PrQqa5gDp+2nBPtx9PwMMWsk1pkapsWJtoi5A3AdpiyjwsdF5LxPqPzYJpBhqndrmOkYl3ALQmmDiwoaAo9F4zK5m8IUv5MP+cV/K1Lu3wzu/ESgP67JJkC6Ny1BLQ26CJBvlbdcVWsAJ0ttSAcl23RV2HgQf9QoEiu3pdEq8tg9aIUvqrOqtrDoFj8YleXfQwiGoh9enGt1UfRSXZoYnmsfk4BMZ2VUNtkrAD9roNy9gygmDAAvgolrmoHneFN59O62JST42aYp7S55zQoCU2sTWpbEOm0lYQCB1ew5dHyfb8gz8KVG2PyvdrEZnxL83QIfYtdrQGZqyzZzLVJceJ9FEtPzSOuyhd8H6A4=
before_install:
- openssl aes-256-cbc -K $encrypted_09207bcf28b9_key -iv $encrypted_09207bcf28b9_iv
  -in config_example.ini.enc -out config_example.ini -d
