language: python
python: 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  user: dileep-kishore
  on:
    tags: true
  password:
    secure: t/cwuAeqYuODLxiASoND+yNQpwAM6eokzJ7w5RuTKVyZpzMBQ72Oj8sKdNPZP+qyCQsp21fDlt020SpFzRsLIYj8p57JfEHrhPw81mg9IJmg9iZN/sGUPPY8LCB8nJBb3puBFam/qRLDV4rc2iKYfuL0T47FhXLWoGGJMTdc+Vw1GGRfpoWZwnbYVyiVAz07UdoXS8rF2EfKDNUjPtfyRWs1UcKkpmBsowukLHlPEEC684z5oHuezxG334LcsDuLmu94CNAk+/Qz83i5aZ+ZpO2yXZn4kMUMC5fEzX4xLedF3CJXBvFKFO4lGKIB8Hfhu8vP8LajcbL5P2mb1iREId2aF+Ju+r3VjhSdRzaHBg3/VGGdGNH6/Q0enAqPRy0XArUNliZWebFaSkOFzW99uwkPTUsx79ym5B5xuk3l6seUdfoPC+KwjRbt5XgX7RMZTXHUzhXUtzu+dGyrblpRIP49JUjC84uSGzH0cNK3vP210fF3FPLsPqtnSfzpkvBxoYlKOAnoIsKcmDyT4NV+zTQJ+btPEb9IQzUUY9pE5QIfAzUzs9QjmpsugXpv0Q15xJ2vkqcn+xuVqlCXFbzqMOeg9gkGL6pFllOXCulFu+mcV1OrD6F7OQh5RiRYWYV8ptyeoK6s8GwN5PiuYidn90pBQgxR4AuRJ4Ht3Kuikhw=
before_install:
- openssl aes-256-cbc -K $encrypted_09207bcf28b9_key -iv $encrypted_09207bcf28b9_iv
  -in config_example.ini.enc -out config_example.ini -d
